### ISSUE TITLE
No Accuracy Metrics

### ISSUE THREAD

**Issue by bpeck81** [perseus784/BvS#3]
This is great work and looks like it took a considerable amount of effort. But, projects like this always include accuracy metrics  to convince others its worth implementing and correct. All I was able to find was "It is actually pretty good. It is almost right all the time. "  It should only take an hour to implement a cross validated accuracy, precision, and recall scores.

**Comment by perseus784** [comment]
Thank you for going through the project. Quite busy this week so, I will update the project with accuracy and precision within the next weekend. I'll leave this issue open till it is updated.
Your feedback is valuable and I highly appreciate you taking time to point a flaw. Thank you!

**Comment by perseus784** [comment]
Hi, sorry for the delay.
So, I actually didn't write it on the repo because I took all the images from the internet and kept only 5 images apart to not to be seen by the model. So, there aren't enough test images. Even if I download it again from the internet, it would most probably belong to the images which are already seen by the model. Also, I just wanted to see the result rather than determining the accuracy at that point in time.

Since you asked, I went to the project again and just recalled why I didn't mention it. With all the images that I have tested, It was right all the time. I even added additional relu and softmax layer to determine the accuracy but It is still giving me a binary result. 

I will definitely keep this in mind for my future projects and if possible I'll add it on this one too. 

Thank you.
